name: "[CI] On Release Creation"
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish to NPM
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node: ["16"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}
      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
