name: "[CI] On Release Creation"
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        uses: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
