name: "[CI] On Release Creation"
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish to NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node: ["16"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install npm dependencies
        run: npm install
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
