name: "[CI] On Tag Creation"

on:
  push:
    tags:
      - "*"

jobs:
  inspection_and_tests_creation_tag:
    name: Inspection and Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node: ["14", "16"]
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm dependencies
        run: npm install
      - name: Run format check with prettier
        run: npm run format:check
      - name: Run lint check
        run: npm run lint

  create_release:
    name: Create Release
    needs: [inspection_and_tests_creation_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
