name: "[CI] Scheduled"

on:
  schedule:
    - cron: "0 0 * * 0-6"

jobs:
  inspection_and_tests_cron:
    name: Inspection and Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ["14", "16"]
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm dependencies
        run: npm install
      - name: Run format check with prettier
        run: npm run format:check
      - name: Run lint check
        run: npm run lint
